base_url = "https://example.com"
author = "cydave"
title = "Cactus Dark"
description = "Hi, I’m a theme for <a href=\"https://www.getzola.org\">Zola</a>. I’m particularly great for a personal web page with a simple blog. In this paragraph, you can provide some information about yourself. Below, your most recent or highlighted writings and projects are listed."
default_language = "en"
generate_feed = true
feed_filename = "rss.xml"
compile_sass = true
build_search_index = true
smart_punctuation = false
taxonomies = [
    { name = "tags", paginate_by = 10 },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"


[extra]
navigation_logo = "/images/logo.png"
navigation = [
    { name = "Home", link = "$BASE_URL" },
    { name = "About", link = "$BASE_URL/about" },
    { name = "Writing", link = "$BASE_URL/blog" },
    { name = "Projects", link = "$BASE_URL/projects" },
]
socials = [
    { name = "github", link = "https://github.com/cydave" },
    { name = "gitlab", link = "https://gitlab.com/cydave" },
    { name = "twitter", link = "https://twitter.com/_cydave" },
    { name = "mastodon", link = "" },
    { name = "facebook", link = "lol" },
    { name = "linkedin", link = "lol" },
    { name = "mail", link = "dave@cyllective.com" }
]
projects = [
    { name = "Zola", description = "A fast static site generator in a single binary with everything built-in.", link = "https://www.getzola.org/" },
    { name = "Font Awesome", description = "The iconic font and CSS toolkit", link = "http://fontawesome.io/" },
    { name = "Bootstrap", description = "The most popular HTML, CSS, and JS framework for developing responsive, mobile first projects on the web.", link = "Bootstrap" },
    { name = "Python", description = "Python is a programming language that lets you work quickly and integrate systems more effectively.", link = "" },
    { name = "D3.js", description = "A JavaScript library for manipulating documents based on data.", link = "https://d3js.org/" }
]
post_date_format = "%d %b %Y"

    [extra.error_404]
    enabled = true
    title = "404 Page Not Found"
    description = "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable."
